#+DATE: <2014-05-07 Wed 09:43>
#+EXPORT: nil

An introvert have I been since I was an infant. My mom says that when I was an
infant, I would cry incessantly while she or my dad were in the room with me at
night. However, as soon as they left me alone I'd quiet down. It is little
surprise that I am still an introvert, though such tendencies are commonly
blunted by our extroverted society. While one of my closest friends fell
squarely on the introverted side in high school, he is now more-or-less an
extrovert after going through college. Me, on the other hand? I can't wait to
get out of here.

* Away from Here

  It's getting more difficult to ignore the urge to simply up and vanish. To
  give Niño and Lucas some contact info and post to Facebook that if anyone
  needs to reach me, go through them, but please don't try to contact me unless
  it's a really big deal.

  Every day at school is emotionally draining. While the engineering complex is
  mostly deserted in the evening, every location is crowded for much of the
  day. If there is one reason that I regret coming to UK, it is the size of the
  place. Then again, a smaller school may not have been any better -- there'd
  be no crowds to hide in.

* Escapism

  My escape hatches for much of my life have been video games and reading. In
  cycles, each has ceased to provide what I desire. Up until this semester, at
  least one of the two had been capable of pulling me out of the world. That is
  no longer the case. Dragging myself through school this year, I have not been
  able to find solace in text or games.

  I've tried a couple of other things. One of note is programming, which has
  provided a surrogate escape hatch at various points during this semester. I
  have determined that I need something to not only asks but flat-out demands
  my entire undivided focus. My constant frustration right now is that I lack
  the time to get into such a focused state while programming, even when I make
  use of the techniques I've learned over the years. In nearly every case, I
  have been interrupted before or soon after I am fully focused.

* Control

  
