#+BLOG: rom
#+POSTID: 296
#+DATE: <2013-12-28 Sat 14:20>
#+TITLE: Echogenetic -- WUBWUB
#+TAGS: music, front line assembly, dubstep, industrial
#+CATEGORY: Music

I finally picked up Front Line Assembly's /Echogenetic/ on Christmas Day this
year. Initially, I was concerned with the direction that FLA was going with
it. I mean, just listen to [[http://www.youtube.com/watch?v%3DXc9POla-hIg&list%3DPLVMVsUomSSJPRAEd-q-HJLxqygw_YV3SA&index%3D7][Killing Grounds]]. It's /dubstep/! My faith in their
abilities, however, was not misplaced.

As I continued listening through the album, [[http://www.youtube.com/watch?v%3D400175d4L5w][Ghosts]] and [[http://www.youtube.com/watch?v%3DXJ-7995sGn4][Blood]] stuck out to me as
proof that FLA's soul is still intact. The vocals are near as strong as they
were in /I.E.D./ and the instrumentation -- while different -- is equally
powerful. As others have noted, the industial metal hints are gone. It'd seem
that Leeb and co's interests have shifted from that genre into dubstep. While my
initial reaction to FLA writing dubstep was "Oh god no!", in the end I'm
thoroughly enjoying the album. As I learned [[http://emallson.wordpress.com/2013/07/19/plastic-makes-shock/][previously]], the initial reaction is
not the one to go off of.

In summary, you could say that I wub it.

I promise to never make that pun again

Recommendation: go [[https://metropolisrecords.bandcamp.com/album/echogenetic][buy it]].

P.S. The [[https://twitter.com/F7A][FLA twitter account]] has some gems like [[https://twitter.com/F7A/status/410804543736139777][this bit of trolling]]. If you're
a fan, you ought to follow it!
