#+TITLE: Home is Where?
#+AUTHOR: J David Smith
#+date: <2014-11-26 Wed 18:48>
#+options: toc:nil num:nil

Last night [[https://storify.com/emallson/spatial-identity][I tweeted up a storm]] about some of my German homework. It was
innocent enough. Read some song lyrics, try to elicit meaning given my limited
vocabulary. Pretty standard stuff. However, this particular song happened to be
/Mein Rostock/ by /Marteria/, which is about the artist's hometown. This led
the questions down a path I was unprepared for.

The questions were innocent enough: "What about you hometown makes you feel at
home?" for example. This is a difficult question for me, because I don't feel
at home here. I've always known this, but it's been relegated to the back of my
mind where it could (hopefully) do no harm. Now I faced it before me.

I spent a solid twenty minutes staring at the blank space below that
question. I briefly considered writing down some vague nonsense, but I couldn't
lie to myself. Ultimately I wrote something to the tune of "Nothing. I do not
feel at home here."

Then I played video games til 4 in the morning.

* A Bit of Today in the First Person

  Today, things were generally better. My mind had settled, had forced that
  thought back out of my mind. For much of the day, that was enough. Much of
  the day.

  My little brothers convinced me to play a game of League of Legends about an
  hour ago. Although my skills have decayed significantly, I'm still
  more-or-less on their level (especially in the jungle). As soon as I logged
  on Mumble, I was greeted with my youngest brother (Jo) talking at his usual
  90 miles per hour. I'm used to it, but normally he stops after a little
  while.

  We queue for a match, and I get thrown into the ADC role. This is blind pick,
  so we don't have any control over their picks. Of course, they include
  Blitzcrank and Zed. Both are nasty to play against as squishy, squishy
  Tristana. Unfortunately, their Blitzcrank was rather good.

  Our lane started off with me getting hooked and barely escaping after blowing
  both Flash /and/ Heal. All the while, Jo is still talking at 90 miles per
  hour and my other brother Seth is responding to questions as Jo fires them.

  I very nearly snapped. Less than 5 minutes in Mumble with them and I leave
  their channel and just sit for a moment, doing nothing in game or reality. I
  switch my playlist from Schwarzblut's latest album to a mix of the later
  T.O.Y./Evil's Toy synthpop albums. Usually, that calms me down. Sure enough,
  Rainbows vs Stars helped. But things felt off, perhaps foreign.

  I insist that we surrender at 20 minutes. By the time the vote passes, I'm
  2/7/2 with abysmal CS. Immediately, Mumble and LoL are closed. I finish my
  half-eaten dinner, and refill the liter Hofbräu mug that I've re-purposed as
  a water glass.

  I fire up steam and immediately close it again. Or at least I tried -- the
  updater popped up moments after I closed the previous window. I let it run,
  leave it open and grab my laptop to write this.

* All Things in Time

  I don't know why I wrote all of that down. I am unsure of a lot of things
  right now. One thing I do know is that I have not recovered from facing this
  truth quite yet: I do not belong here.

  There have been a few times that I've been more-or-less comfortable. This
  summer, working with the great people in ExtremeBlue at IBM. These days, when
  hanging out in the ACM room at UK. Thinking back, that actually about sums it
  up. Regardless, the feeling of belonging is always broken. Almost always by
  some small, off-hand comment with large, unintended consequences.

  It's ok, though. I have the twin questions of "Where do I belong?" and "Why
  not here?". I do not know the answer to either. In truth, the second question
  bothers me more. Regardless, I know one thing: I will learn the answers, or
  will discard the questions. Why do I know this? Simple: everything works
  out. Everything /always/ works out -- just not in the way one might expect.

* A Small Post-Script

  I tend to be very anti-social, but I feel the need now to express gratitude
  to my friends just now. There may not be a place that I feel at home, but
  they are the people that I can turn to. One of them messaged me last night
  after my tweet-storm to see if I was okay. That meant a lot to me. More than
  I knew then. It's all the small things, really. All the small things.
