#+title: Introversion: Seeking Balance
#+options: toc:nil num:nil
#+date: <2014-08-04 Mon 20:48>

On Saturday I was riding back home from dinner with friends. It was rather late
-- near eleven -- yet the sky was still surprisingly bright. It held a bit of a
purplish color that hinted that we'd see more storms, which was no surprise
given the recent weather. Staring out the passenger-side window of my friend's
car, I suddenly felt an incredible sense of vertigo. For a split-second, the
scene outside the window had mirrored that of a dream I had when I was around
10 years old.

* The Dream

  Of course, it wasn't an exact match, but it was close enough that my mind drew
  a connection. My eyes teared up as the long forgotten memories suddenly forced
  their way to the forefront of my mind. For a moment, I relived the dream. Then
  it fled -- just as quickly as it had all those years ago.

  In my dream, I was on a dirt path deep within a pine forest. It was night, and
  the clouds held a beautiful purple hue. The power of a coming storm made the
  air buzz more than the incessant sound of insects did. Aside from said insects,
  the forest was silent.

  As the dream fled from me, I felt a heavy longing settle over me. I wanted to
  be there, to bask in the beauty of the forest and the power of the storm. To
  exist -- if only for a moment -- in that most beautiful environ. Before long,
  my contemplation led to the realization of how much I miss the forests.

* The Woods and I

  I didn't have much exposure to woods growing up. My home was on the outskirts
  of a small city for most of the first 13 years of my life. We had a couple of
  trees, but nothing much. On occasion, we went camping. I always complained
  about it (as all children do), but I still liked it. Most of my experience with
  the woods comes from playing in the trees out back of my friend Brandon's home.

  Brandon lived at most a mile from the Kentucky River. Behind (in one sense of
  the word /behind/) his home, there was a great mass of trees stretching off
  into the distance. We often went exploring in these woods, trekking to the
  river and back in zigzagged patterns. Once we went alongside the river until
  we came to a long rocky slope cutting right across our path. We hadn't
  realized how long we'd been gone until sunset arrived and quickly began
  departing. Our mothers weren't very pleased with our little adventure, seeing
  as we didn't make it back til nearly dark.

  Over time we became more interested in video games than exploring the
  woods. This was partly because we'd already seen much of them, and partly
  because video games offered more to explore. I don't regret that shift in
  priorities, but I do miss the trees.

* Alone-ness: My Paradoxical Longing

  Introversion is a definitive aspect of my personality. It has displayed
  prominently ever since I was an infant. In fact, I have been told that as an
  infant I would cry incessantly when put to bed -- until everyone left the
  room, at which point I would immediately calm down. Were my mom or dad to
  re-enter the room, I would begin bawling my eyes out again.

  This dream reminded me of how much I miss being alone in a way that no city
  can provide. In the woods, I am alone. When I am alone, I am free. At the
  same time, I cannot help but remember the objective I held in the
  dream-forest: finding my friends. Among the fleeting trees, I sought
  companionship. I longed for it even as I now long to be alone.

* The Importance of Balance

  Ultimately, this experience has served as a reminder to me that I'll not be
  happy until I find my balance. I have often contemplated seeking out a
  hermitage. It has been a 'not now, but maybe' train of thought in recent
  years. While I now believe that a hermitage might be taking things a bit too
  far, it is certainly the right direction.

  While at school this past year, I increasingly felt the need to escape from
  the constant press of humanity. During this summer, I have found much
  respite, despite the fact that I am constantly surrounded by people. This is
  largely due to a difference in density: here I am surrounded by people, but
  in small quantities -- unlike on campus, where even a walk through the
  engineering complex can take me past more than a hundred people easily. I
  dread the great mass of humanity more than anything else as I contemplate
  returning to school.

  Even still, I have felt the need to escape during this summer. Certainly, my
  current environment is a step in the right direction, but it is not enough. I
  must be constantly wary of overshooting my target, but I cannot yet say that
  I have found the proper balance. Now I must wonder: will I be able to?
