#+BLOG: Record of Motion
#+POSTID: 329
#+DATE: <2014-01-03 Fri 10:00>
#+TITLE: Reflections from 2013: A Stiff Kick in the Rear
#+CATEGORY: Life, Music
#+TAGS: music, reflections, the birthday massacre, zeromancer

One of my most-listened-to songs of 2013 (and quite possibly all time) is The
Birthday Massacre's [[http://www.youtube.com/watch?v%3Dt8uuThyr3hI][remix of Last Daze]] (original by Left Spine Down). If you
listen to the lyrics, you'll find that they're actually quite sad. Take, for
example, the chorus:

#+BEGIN_QUOTE
    Come waste away now your last days \\
    Sign away your life today
#+END_QUOTE

That's some pretty dark stuff, and yet somehow the song always gives me a
buzz. It's like caffiene, but I don't have to keep buying more. There are two
reasons for this: first, the instrumentation and song structure is insanely
good. The whole thing just screams of power. TBM has a reputation for really
hitting things out of the park, but I am struggling to imagine them conjuring
something that can top this (of course, when they do my mind will be blown).

The second reason is that I'm one of those odd people for whom the lyrics of a
song often have inverse effects. Happy song? I invariably come out feeling kinda
down. Sad song? I feel freakin' awesome. As another example take Zeromancer's
[[http://www.youtube.com/watch?v%3DxDSA9ha3pwY][Eurotrash]] or [[http://www.youtube.com/watch?v%3DixskugIPSSQ][Doctor Online]]. Both are really sad -- some would say disturbing --
songs, but neither of them make me feel sad or disturbed. If I listen to one
while sad, I end up feeling better after. Weird, right?

In some ways it's like the relatively common trope in fiction wherein a
secondary character declines aiding the protagonist. Cue antagonist antagonizing
said secondary character. Shortly thereafter, s/he agrees to help the
protagonist. The antagonist here is the musician and the antagonization the
music. I'd be the secondary character. Who's the protagonist then? Life. The
music is like a stiff kick in the rear, telling me '/get moving!/'

And I listen.
