#+BLOG: Record of Motion
#+POSTID: 309
#+DATE: [2014-01-01 Wed 11:25]
#+TITLE: Reflections from 2013: A Blade Called Regret
#+CATEGORY: Music, Life
#+TAGS: music, reflections, resolution, assemblage 23, regret

As I told a group of friends last night, 2013 was a really eventful year for
me. A lot of things happened that deeply impacted me and changed how I viewed
the world, myself, and my future. I intend to write a fair bit not about what
happened (though that will certainly come into it), but about what I
learned. I'm not going to do this in an ordered fashion, so without further ado:
Regret.

Regret is a funny thing. Sometimes, one feels like one ought to be regretful but
one isn't; other times one is regretful but feels that they shouldn't be. I've
had people tell me to "just let it go" and "don't look back". While they've got
the action right, they have never given me a reason why this is the right action
beyold "you won't be happy otherwise."

Assemblage 23's [[http://www.youtube.com/watch?v%3DSvV-xFsXCls][/Regret/]] has one of the most potent descriptions of regret that
I've ever heard:

#+BEGIN_QUOTE
    Regret is a dull and rusted blade
    That covers me with scars that never fade
    These wounds: a catalogue of flaws
    Serve to remind me of all the pain I've caused
#+END_QUOTE

My initial understanding was of both the scars and the blade representing
regret. However, right before the fall semester began +this+ last year I
realized that only the blade is regret, not the scars. What then, are the scars?
To answer this, one must first ask: who wields the blade? The answer: I do.

This singular realization changed how I viewed the question entirely. The blade
is not wielded by a phantasm of my past, but by me and me alone. The picture is
now clear to me: willful self-mutilation. That is regret. Each mistake is
another cut, another scar much akin to a fabled hunter notching his bow or
adding another tooth to his necklace for every kill.

With this in mind, the reason for why one ought not look back, why one ought put
down the blade called regret is less that one won't be happy otherwise and more
to prevent one from inflicting self-harm. Put simply: [[http://www.youtube.com/watch?v%3DabEBbI06w8M][stop hittin' yourself!]]
