#+BLOG: Record of Motion
#+POSTID: 334
#+DATE: <2014-01-07 Tue 08:49>
#+TITLE: Reflections on 2013: Otherness and My Resolution
#+CATEGORY: Life, Music
#+TAGS: assemblage 23, music, reflections, resolution, otherness

The song with the most significant impact on my life in 2013 -- and possible
ever -- was Assemblage 23's [[http://www.youtube.com/watch?v=azr7c5a_x9c][Otherness]]. This song is the perfect description of
the person I didn't know I wanted to be.

The summary of this behavior is found in the sixth verse ([[http://www.assemblage23.com/bruise][lyrics]]):

#+BEGIN_QUOTE
[It] Is altruism
In its purest form
A kind of otherness
From which ego is torn
#+END_QUOTE

Starting at the bottom: this is behavior without ego. Ego never enters the
equation. This ego is not the technical Freudian definition, but rather the
common definition of [[http://www.thefreedictionary.com/ego][the self]]. The intent is to reflect, as the first two lines
state, the purest altruism. In my opinion, it does so quite well.

The usage of the word /otherness/ nicely captures how such behavior would move
one almost into an ethereal plane. Few of us are unfamiliar with such actions,
but most all of us are unfamiliar with individuals who are so consistently
altruistic that they are almost angelic.

It isn't simply about being a Mother Teresa either; it involves every action one
performs and every response one gives. This is the ultimate goal for me, and one
which I probably will never attain: always acting and reacting in kindness,
always being relaxed, always being calm. /Where did you get the latter two?/ one
might ask. The answer is simple: trust.

#+BEGIN_QUOTE
To trust completely
With an open heart
To risk the wounds
Of having it all fall apart
#+END_QUOTE

Complete trust begets calmness and relaxation. I am nowhere near this goal, but
I intend to keep trying. This is my resolution. After all, as the saying goes:

#+BEGIN_QUOTE
Shoot for the moon! Even if you fail, you will end up among the stars.
#+END_QUOTE
