#+TITLE: Wot I Think: Heroes of the Storm Technical Alpha
#+AUTHOR: J David Smith
#+DATE: <2014-05-23 Fri 14:13>
#+OPTIONS: toc:nil num:nil
#+EXPORT: nil

  Right as I was ramping up my studies for finals, I got an email from Blizzard
  informing me that I'd been selected for the /Heroes of the Storm/ Technical
  Alpha. "Fantastic!" I thought to myself, "and perfect timing, to boot! I need
  more distractions this week!" So I put off installing it like the boring,
  responsible student I am.

  Once I had survived finals (with all A's, no less! ^.^), I got the download
  going. Gotta say one thing: getting set up for Blizzard alpha/beta games is
  super-easy with their unified launcher. I literally just clicked 'Install',
  selected a location, and was done save for the download itself.

  As I'm going through wot I think of the game so far, keep in mind that it's
  still in Technical Alpha. Also, I've only played somewhere between 20 and 30
  games so far: enough for a 'First Impressions' but not a full-on review.

* Presentation

  One of Blizzard's strong points has always been their excellent
  presentation. Due to artwork that relies heavily on stylization over poly
  counts, their games tend to look surprisingly good even on low-end hardware. 

** Performance

   The system I'm playing on is getting a bit dated. The important specs are:

   - Intel Core 2 Quad 2.66 GHz
   - 4GB DDR3 RAM
   - nVidia 560 GTX

   Passable, but not particularly powerful. I have been playing the game on
   Medium or High settings depending on the match. Performance has varied
   from match to match, but overall has been very good -- most of the
   time. Some +champions+ heroes hurt my framerate more than others; the
   difference makes sense, as some (ex: Diablo) are much more particle-heavy
   than others (ex: Nova). Considering that this is an alpha, I was pleasantly
   surprised at the generally consistent framerates.

** Graphics & Style

   Blizzard has continued in their path of very stylized graphics. While some
   models seem more-or-less ripped from their respective games on the surface,
   the ones I've seen appear to have been tweaked to better fit the style of
   the game. That said, it will *always* look funny to see Diablo riding a
   horse. Poor horse.

** Sound

* Gameplay

   While on the surface /Heart of the Storm/ is quite similar to other
   contemporary MOBAs, the similarities are only at the mechanical level. The
   game is played in 5v5 competitive matches from an isometric perspective with
   RTS-style click-to-move controls. The core gameplay is roughly the same as
   /League of Legends/ or /Defense of the Ancients/. However, several systems
   changes have dramatically altered the dynamic.

** Prepare to be Broke

   The first of these is removal of gold as a resource. This has the effect of
   reducing the snowball effect. While snowballing still occurs for reasons
   I'll discuss in a moment, it is not nearly as severe as in /LoL/ or
   /DotA/. The removal of this system entirely has not been without
   controversy. However, it has received a suitable replacement for
   customization in the Talent system.

** Talented, Aren't We?

   Every few levels (starting at 1), players are given the option of 2-4
   talents. These range from passives like /Path of the Wizard/, which grants
   increased mana and mana regeneration, to the choice of +Ultimate+ Heroic
   abilities at level 6. Players are not able to change talents during a match
   -- only choose them -- but they are reset after every match, in classic MOBA
   style.

   I should make it clear that the talents are chosen in a style similar to
   /WoW/'s current system: you are given 2-4 choices and must take one (and
   only one). You can't take 2 from tier 1 and none from tier 2 or any of that
   chicanery. Come to think, I should test and see what happens if I don't take
   any talents when more are offered. 

   With this system, experience has effectively replaced gold as the currency
   du jour. Talents offer raw stat buffs as well as interesting active effects
   (such as Malfurion t2 offering an OP as fuck shield spell). However, this
   means that we won't ever see crazy builds like AP Rengar. Then again, I
   would be much happier if I'd never had to deal with the BS that was AP
   Yi. Win some, lose some.

   Overall, I'm pretty excited about the talent system. I don't feel like it
   restricts my options much during play, while it eases the introductory
   learning curve significantly and has potential to reduce the frequency of
   significant balance issues.

** Team-wide Experience

   Another important change is Blizzard's move from per-hero experience to
   per-team experience. No hero (even those AFK) is left behind in this
   system. However, it does make it so that a bad player can impact your
   performance much more quickly. Both player and minion kills give experience
   -- but only if someone on your team is in range. Therefore, if another lane
   is feeding then not only is their lane gaining an advantage, but yours is as
   well. Additionally, because the feeding lane is going to spend more time
   dead (and thus away from the creeps) your entire team will fall behind in
   experience.

   This isn't as disastrous as it sounds. The most significant difference I've
   ever seen in levels is 4. I've heard that there are catch-up mechanics in
   place, but I've not done the research to confirm or deny this
   hearsay. Regardless, being 4 levels behind is about as bad as being 4 levels
   behind in /LoL/: painful, but not insurmountable. It's nowhere near "our bot
   lane went 0-20 in 10 minutes" bad, as the occasional /LoL/ game will be.

** Maps

   The map design and implementation is also considerably different from
   classic MOBAs. Where /LoL/ and /DotA/ effectively have only one map with
   only one mode, /HotS/ has 4 as of this writing -- each with its own
   secondary objectives. This is similar to how /Guild Wars 2/ has several
   different maps with the same primary objective (king-of-the-kill; win at 500
   points) but disparate secondary objectives (kill boss mobs for extra points,
   invade enemy base for lots of points, control catapults).

   The primary objective is the same as in /LoL/ / /DotA/: destroy the enemy
   +ancient+ +nexus+ core. The method of attaining this objective is, again,
   similar: farm and push. However, there is a significant twist common to all
   maps: mercenaries.

** This Ain't Your Daddy's Jungle

   Where /LoL/ / /DotA/ (henceforth abbreviated as /LotA/) have neutral camps
   scattered in the 'jungle' between the lanes, /HotS/ has Mercenary
   camps. These camps are significantly more difficult than their counterparts
   in /LotA/, but they do not scale in level as the game progresses like they
   do in /LoL/. When a camp is killed, a capture point becomes
   available. Obtaining control of this point will spawn a band of mercenaries
   that will push on your team's behalf and put the camp on a ~3 minute
   cooldown.

   What results is a pretty clever solution to the game length problem: pushing
   becomes considerably easier as the game progresses without snowballing
   causing one team to dominate the other in team-fights. Adding in secondary
   objectives is really just icing on the cake -- I'd be happy to play a mode
   lacking them.

   The secondary objectives in /HotS/ are varied enough that -- provided the
   RNGods favor you -- the game stays fresh even when playing the same hero
   over and over again. One map features two shrines that, when controlled by
   your team, allow one team-member to transform into a powerful
   dragon. Another has players traveling under the map in a mine full of
   undead, collecting skulls to summon powerful golems. Yet another asks us to
   fight mercenary camps and bust open treasure chests to pay a greedy pirate
   captain to bombard the enemy base with his cannons. While some still need
   tuning (it is very difficult to come back from being hit with a team-wide
   curse that reduces all of your creeps' HP to 1, reduces structure HP by
   half, prevents turrets from firing, and prevents natural HP regeneration),
   they certainly provide interesting gameplay.

   Notably lacking right now is a Starcraft-themed map. The others are
   fantasy-themed -- not even really Warcraft- or Diablo-themed, which is kind
   of disappointing. This is one area that I feel /Heart of the Storm/ is
   really lacking in right now. While the characters belong to well-defined
   universes, the maps don't really belong anywhere. I'd like to see the
   existing maps changed to fit better into one of the existing Blizzard
   universes. This would make the game as a whole feel more cohesive.

** Balance

   MOBA games tend towards a certain balance level at early stages of
   development. /Heroes of Newerth/, as an example, was more-or-less balanced
   with the exception of a handful of heroes that were completely over the
   top. In my experience, this is pretty common. The underlying mechanics are
   well-understood, but it is still quite easy to over-tune a hero and turn it
   into a walking murder machine.

   /Heart of the Storm/ does not have this in my experience. Certain map
   mechanics need re-balancing right now (Undead Mines and Curse of the Raven
   Lord), but I've never seen a hero that just made me shout "that is
   bullshit!" -- except for Nova.

** The Stealth Problem

   Nova has a lot of things going for her: decoys, stealth, high damage, high
   range. Meanwhile, she is super-squishy to help balance things out. This
   would normally work fine, except for stealth. In /HotS/, stealth works like
   its /Starcraft II/ incarnation: predator-style shimmer around you, not true
   invisibility. Stealth automatically activates after 2 seconds of not taking
   damage.

   *2 seconds*

   This is only a problem because there is not a good way to stick on her for
   many heroes. One bad choice by the pathing algorithm pretty much means that
   she's gone unless you're ranged or have a low-cooldown gap closer (because
   you probably blew it to reach her the first time). Even this wouldn't be a
   problem if the stealth worked entirely as advertised.

   This kind of stealth is really cool in concept, except that it suffers from
   a very odd problem: what to do on low-power machines. The predator-style
   effects are expensive. Thus, there are three choices Blizzard could make
   about this:

   1. Leave them on for all machines, potentially causing significant FPS loss
      on low-power machines.
   2. Turn them off on low-power machines, turning stealth into true
      invisibility.
   3. Swap them for a cheaper but less subtle effect on low-power machines,
      making stealth less reliable against people playing on the lowest
      setting.

   I am honestly not sure which one Blizzard is using right now.

* Conclusion
